templates/svix-lib-python/types/struct.py.jinja
- Use alias_geneator instead of explicitly defining the aliases
- Correctly handle the nullable types
=> python: Refactor pydantic based models

src/generator.rs, src/main.rs
Allows auto-completion of template files on the command line.
=> Stop prefixing template path with 'templates/'

src/api.rs, src/generator.rs
For some resources (for example op webhooks) The parent resource does not have any operations and an empty API file is generated.
=> Don't generate api resource files if the resource has no operations

src/postprocessing.rs, src/template.rs, src/types.rs, templates/svix-lib-kotlin/api_extra/application_create.kt, templates/svix-lib-kotlin/api_extra/message.kt, templates/svix-lib-kotlin/api_resource.kt.jinja, templates/svix-lib-kotlin/component_type.kt.jinja, templates/svix-lib-kotlin/types/integer_enum.kt.jinja, templates/svix-lib-kotlin/types/string_enum.kt.jinja, templates/svix-lib-kotlin/types/struct.kt.jinja
Steps:
ref:
- https://github.com/svix/monorepo-private/issues/9675
- https://github.com/svix/monorepo-private/issues/9685
- https://github.com/svix/monorepo-private/issues/9686
=> kotlin: Add jinja templates for codegen

templates/svix-lib-go/types/struct.go.jinja, templates/svix-lib-kotlin/types/struct.kt.jinja
Ensure that nullable fields can be set to `null` on `ListResponse*Out` models
=> Correctly handle nullable fields

src/generator.rs, src/postprocessing.rs, src/types.rs, templates/svix-lib-javascript/api_extra/application_create.ts, templates/svix-lib-javascript/api_resource.ts.jinja, templates/svix-lib-javascript/component_type.ts.jinja, templates/svix-lib-javascript/component_type_summary.ts.jinja, templates/svix-lib-javascript/types/integer_enum.ts.jinja, templates/svix-lib-javascript/types/string_enum.ts.jinja, templates/svix-lib-javascript/types/struct.ts.jinja
_almost_ working. I've explained @svix-lucho the state of things so this can be finished while I'm away.
Reflected in https://github.com/svix/svix-webhooks/pull/1700.
=> js: Add type templates

src/main.rs
Only generate the `.codegen.json` file if the `--write-codegen-metadata` was specifed
=> Add `--write-codegen-metadata` option

src/generator.rs
=> Use fs_err::read_to_string instead of std::fs::read_to_string

src/generator.rs
New template kind `summary`
This template has access to `api` and `types`, Used in our Ruby lib to generate this [file](https://github.com/svix/svix-webhooks/blob/aa40c6d1a5dea4f2afc4415a8909eb9109e784a0/ruby/lib/svix.rb)
=> Refactor summary generation to include both `api` and `types`

.github/workflows/docker-release.yml, Dockerfile, src/generator.rs, src/main.rs, src/postprocessing.rs
This PR adds a arm64/amd64 docker image that include
- `openapi-codegen`
- `rustfmt +nightly` (Rust)
- `biome` (JS/TS)
- `ruff` (Python)
- `google-java-format` (Java)
- `ktfmt` (Kotlin)
- `rubyfmt` (Ruby)
- `goimports` (Go)
- `gofmt` (Go)
- `csharpier` (C#)
The `docker-release.yml` workflow builds and releases a new image on every push to main
The images are pushed to `ghcr.io/svix/openapi-codegen` with tag `latest` and `<date>-<git rev-parse --short>` (`20250228-ffac537`)
I build the `arm64` image using `ubuntu-24.04-arm` [runners](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/)
There is a little bit of a hack I have to do to get 2 separate builds for `arm64`/`amd64` published under the same tag
But this …
=> Add docker build with all formatting tools

src/api.rs, src/generator.rs
Reverts svix/openapi-codegen#63
We want these files, we just need to update the templates to actually generate useful contents.
=> Revert "Don't generate api resource files if the resource has no operations"

Cargo.lock, Cargo.toml, src/generator.rs, src/template.rs
get_temp was introduced in version 2.8.0
Limited to 1 extra file per generated component type, but I am happy with that
The extra file is a hack, I don't care about making it more robust
=> Postprocess extra generated file

src/api.rs, src/main.rs
Keep the same default behavior to only include public operations
Will be useful when we generate the internal JS lib for frontend 
help
```
Options:
--include-mode <INCLUDE_MODE>
Which operations to include
[default: only-public]
Possible values:
- only-public:       Only public options
- public-and-hidden: Both public operations and operations marked with `x-hidden`
- only-hidden:       Only operations marked with `x-hidden`
```
=> Add `include-mode` to select which operations to include

src/api.rs, src/main.rs, src/postprocessing.rs
Allows me to only include operations from a specified list of operations, This will be helpful when I generate the internal JS lib
=> Add new option `--specified-operations`

src/api.rs, src/main.rs
Specify a list of excluded operations
Final blocker for the internal JS lib
=> Instead of an ever growing list of included operations

.github/workflows/docker-release.yml
Need to set `mode=max` to cache the intermediate build steps. And since we are building a bunch of stuff from source (rubyfmt) caching intermediate steps is important 
https://docs.docker.com/build/cache/backends/#cache-mode
=> Enable caching on build steps

src/api.rs
Same as the separator between operation ID segments. This does not affect any of the existing templates here or in svix-webhooks.
=> Change subresource separator from - to .

.github/workflows/docker-release.yml, Dockerfile
I had this as a local branch for a while but for some reason never opened a PR
This will speed up build times
=> Download a pre-built rubyfmt instead of building it from source

src/api/mod.rs
The previous implementation would only keep one definition of a top-level resource if found in multiple input files.
=> Properly merge multiple input files

.gitignore, src/api/mod.rs, src/api/struct_enum.rs, src/api/types.rs, src/template.rs
Allows the codegen to build struct enums with inline structs 
```rust
enum Foo {
Bar {
baz: String
}
}
```
Previously only this was supported 
```rust
enum Foo {
Bar(BarConfig)
}
struct BarConfig {
baz: String
}
```
See this PR for example struct enum: https://github.com/svix/monorepo-private/pull/10973 (`frontend-codegen/src/models/streamSinkPatch.ts`)
=> Add support for struct enums with inline fields

src/postprocessing.rs
this new option will take
`import { MessageIn } from "../models/index";`
and convert it to
`import type { MessageIn } from "../models/index";`
(only if it's only used as a type)
please see this commit for the resulting codegen diff: [svix/svix-webhooks@`04bb697` (#2072)](https://github.com/svix/svix-webhooks/pull/2072/commits/04bb69753c65be885df59c14a98390e089ca0949)
=> Automatically prefix type only imports with `type`

Dockerfile
For now I am just adding them to the docker image, They will be used as part of the codesample generation.
=> Add `golines` and `gofumpt` as formatting tools

.github/workflows/docker-release.yml, Dockerfile
We currently use `google-java-format`, and it's quite ugly. 
Instead I am going with `palantir-java-format`, it looks much nicer.
I am keeping both, and for now I will only use `palantir-java-format` on the code samples
Before
```java
var response =
svix.getAuthentication()
.appPortalAccess(
"app_1srOrx2ZWZBpBUvZwXKQmoEYga2",
new AppPortalAccessIn()
.application(
new ApplicationIn()
.metadata(Map.of())
.name("My first application")
.rateLimit(1L)
.uid("unique-identifier"))
.capabilities(
Set.of(
AppPortalCapability.VIEW_BASE,
AppPortalCapability.VIEW_ENDPOINT_SECRET))
.expiry(1L)
.featureFlags(Set.of())
.readOnly(true)
.sessionId("user_1FB8"));
```
After
```java
var response = svix.getAuthentication()
.appPortalAccess(
"app_1srOrx2ZWZBpBUvZwXKQmoEYga2",
new AppPortalAccessIn() …
```
=> Add `palantir-java-format` as a formatter
