src/api.rs, src/main.rs
… and add a flag for including them.
We currently have some operations we want our old codegen to generate code for, but we don't want to run the new (higher-level) APIs for.
=> Exclude operations with x-hidden by default

src/types.rs
Prep for adding JS model templates.
=> Finish to_js_typename implementation

templates/svix-lib-go/api_extra/message_attempt_list_attempted_destinations.go
From last week, not sure why I didn't actually submit the PR.
cc @svix-onelson
=> go: Add another api_extra file

src/types.rs
… and structs that contain a struct enum as an auxiliary type, because we actually have relevant spec types that contain both `oneOf` and `properties`.
=> Add support for struct enums (oneOf)

src/types.rs, templates/svix-lib-kotlin/api_resource.kt.jinja, templates/svix-lib-kotlin/types/struct.kt.jinja
[kotlin: Change JsonObject to Map<String,Any>](https://github.com/svix/openapi-codegen/commit/5b6eff16a1617f481bb644449fc0ffebaf10d01f)
[kotlin: Add doc comments](https://github.com/svix/openapi-codegen/commit/721cea7b9c97e04487eb828af2de984aa4d6584f)
=> kotlin: Add some fixes to our codegen

templates/svix-lib-rust/types/struct.rs.jinja
ref: https://github.com/svix/svix-webhooks/pull/1722
ref: https://github.com/svix/svix-webhooks/issues/1721
=> rust: Fix optional fields

src/generator.rs, templates/svix-lib-go/component_type_summary.go.jinja
=> go: Export component type summary

src/generator.rs, src/postprocessing.rs
Some post-processors are unable to scan a directory tree and then process each file, rather they have to get each file as a CLI arg This causes the codegen to execute the post-processor once on every generated file
After this refactor, we collect the path to each generated file into a Vec, And once all of the files were generated we execute the post-processor once.
=> Refactor postprocessing to make it faster

Cargo.lock, Cargo.toml, src/api.rs
Remove unused stuff, upgrade dependencies.
=> Some cleanup

templates/svix-lib-javascript/types/struct.ts.jinja
ref: https://github.com/svix/svix-webhooks/pull/1757
=> js: Fix issues causing `_fromJsonObject` to panic at runtime

src/generator.rs, src/postprocessing.rs, src/template.rs, src/types.rs, templates/svix-lib-ruby/api_extra/application_create.rb, templates/svix-lib-ruby/api_extra/message.rb, templates/svix-lib-ruby/api_resource.rb.jinja, templates/svix-lib-ruby/component_type.rb.jinja, templates/svix-lib-ruby/summary.rb.jinja, templates/svix-lib-ruby/types/integer_enum.rb.jinja, templates/svix-lib-ruby/types/string_enum.rb.jinja, templates/svix-lib-ruby/types/struct.rb.jinja
ref: 
- https://github.com/svix/monorepo-private/issues/9599
- https://github.com/svix/svix-webhooks/pull/1753
=> Add ruby templates

.github/workflows/docker-release.yml
We use the same Dockerfile for both arm64/amd64
=> Fix broken CI

Dockerfile, src/api.rs, src/generator.rs
The `goimports` cli needs a whole go install in the PATH
=> `goimports` needs a whole install available

.github/workflows/docker-release.yml
The tag will look like this
`20250304_163519-267`
I don't know why I kept it to only date, I feel like one day we will release more then 1 tag. And it will be confusing which tag is the latest
=> Add time to docker tag, and use UTC

.github/workflows/docker-release.yml
See latest [image](https://github.com/svix/openapi-codegen/pkgs/container/openapi-codegen/367317872?tag=20250304-1)
=> Use  ${{ github.sha }} instead of HEAD

.github/workflows/docker-release.yml, Dockerfile, src/postprocessing.rs
Reduces the image size from 1.9gb to 700mb
Also fixes issue where depth of git history would not show up correctly
=> Add new alpine based image

src/generator.rs, src/template.rs
Also add output_dir to component_type context
=> Add `generate_extra_file` jinja function

Dockerfile
We don't need to target musl, `gcompat` allows us to use glibc programs on alpine
=> Enable docker layer caching with cargo chef

src/types.rs
=> Make color a string

src/api.rs, src/main.rs
This mode works in tandem with `--include-op-id`.
It will be used in the Go lib. Allowing me to generate an _only_ the internal API methods I need for terraform
=> Add new include mode `OnlySpecified`

Dockerfile
https://github.com/svix/openapi-codegen/actions/runs/14456758403/job/40541608893
This is the line with the error: https://github.com/svix/openapi-codegen/actions/runs/14456758403/job/40541608893#step:5:347
=> Fix weird bug with apk, a package was missing from cache???

Cargo.lock, Cargo.toml, src/debug.rs, src/main.rs
… in a single `debug.ron` file. This is preparation for being able to use this format as an input as well.
=> Switch --debug from Debug output to actual RON

src/api/mod.rs, src/api/resources.rs, src/main.rs
=> Allow specifying multiple input files

Dockerfile, src/generator.rs, src/postprocessing.rs, src/template.rs
=> Switch to `@Symfony` for php style

src/main.rs
Follow-up to #130. Turns out we're already on Edition 2024.
=> Use let chains for new bit of code
